package spielrechner;

import java.awt.*;
import javax.swing.*;

public class Rechner extends JFrame {
    private Operator operator;
    /**
     * Creates new form Rechner
     */
    public Rechner() {
        initComponents();
        init();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        sliderZahl1 = new javax.swing.JSlider();
        textZahl1 = new javax.swing.JTextField();
        buttonPlus = new javax.swing.JToggleButton();
        buttonMinus = new javax.swing.JToggleButton();
        buttonMal = new javax.swing.JToggleButton();
        buttonDurch = new javax.swing.JToggleButton();
        textZahl2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonErgebnis = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        textErgebnis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rechner");
        setResizable(false);

        jLabel1.setText("Zahl 1");

        sliderZahl1.setMaximum(999999);
        sliderZahl1.setValue(0);
        sliderZahl1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderZahl1StateChanged(evt);
            }
        });

        textZahl1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textZahl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textZahl1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonPlus);
        buttonPlus.setText("+");
        buttonPlus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonPlusStateChanged(evt);
            }
        });

        buttonGroup1.add(buttonMinus);
        buttonMinus.setText("-");
        buttonMinus.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonMinusStateChanged(evt);
            }
        });

        buttonGroup1.add(buttonMal);
        buttonMal.setText("x");
        buttonMal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonMalStateChanged(evt);
            }
        });

        buttonGroup1.add(buttonDurch);
        buttonDurch.setText(":");
        buttonDurch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonDurchStateChanged(evt);
            }
        });

        textZahl2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textZahl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textZahl2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Zahl 2");

        buttonErgebnis.setText("Ergebnis");
        buttonErgebnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonErgebnisActionPerformed(evt);
            }
        });

        buttonClear.setText("C");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        textErgebnis.setEditable(false);
        textErgebnis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textErgebnis.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textErgebnis)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonErgebnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderZahl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonPlus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMinus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDurch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textZahl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(textZahl1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textZahl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderZahl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPlus)
                    .addComponent(buttonMinus)
                    .addComponent(buttonMal)
                    .addComponent(buttonDurch)
                    .addComponent(textZahl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonErgebnis)
                    .addComponent(buttonClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textErgebnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textZahl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textZahl1ActionPerformed
        try {
        sliderZahl1.setValue(Integer.parseInt(textZahl1.getText()));
        } catch (NumberFormatException ex) {
            textZahl1.setText(""+sliderZahl1.getValue());
        }
    }//GEN-LAST:event_textZahl1ActionPerformed

    private void sliderZahl1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderZahl1StateChanged
        textZahl1.setText(""+sliderZahl1.getValue());
    }//GEN-LAST:event_sliderZahl1StateChanged

    private void buttonErgebnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonErgebnisActionPerformed
        int zahl1 = sliderZahl1.getValue();
        double zahl2 = Double.parseDouble(textZahl2.getText());
        textErgebnis.setText(""+operator.calc(zahl1,zahl2));
    }//GEN-LAST:event_buttonErgebnisActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
       init();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonPlusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonPlusStateChanged
        if (buttonPlus.isSelected()){
            operator = Operator.PLUS;
        }
    }//GEN-LAST:event_buttonPlusStateChanged

    private void buttonMinusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonMinusStateChanged
        if (buttonMinus.isSelected()){
            operator = Operator.MINUS;
        }
    }//GEN-LAST:event_buttonMinusStateChanged

    private void buttonMalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonMalStateChanged
        if (buttonMal.isSelected()){
            operator = Operator.MAL;
        }
    }//GEN-LAST:event_buttonMalStateChanged

    private void buttonDurchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonDurchStateChanged
        if (buttonDurch.isSelected()){
            operator = Operator.DURCH;
        }
    }//GEN-LAST:event_buttonDurchStateChanged

    private void textZahl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textZahl2ActionPerformed
        textZahl2.setText("0.0");
    }//GEN-LAST:event_textZahl2ActionPerformed
private void init(){
     sliderZahl1.setValue(0);
        textZahl2.setText("0.0");
        buttonPlus.setSelected(true);
//        operator = Operator.PLUS;
        textErgebnis.setText("");
        textZahl1.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rechner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JToggleButton buttonDurch;
    private javax.swing.JButton buttonErgebnis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton buttonMal;
    private javax.swing.JToggleButton buttonMinus;
    private javax.swing.JToggleButton buttonPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider sliderZahl1;
    private javax.swing.JTextField textErgebnis;
    private javax.swing.JTextField textZahl1;
    private javax.swing.JTextField textZahl2;
    // End of variables declaration//GEN-END:variables
}
